# Evaluation-only pipeline
# This pipeline is intended to be run by pipeline_evaluator.coffee
# It assumes training runs have already produced outputs under run/*

pipeline:
  steps:

    pre_eval:
      run: scripts/042_pre_eval.coffee
      depends_on: []

    # Step 3: Final evaluation report and policy generation
    eval:
      run: scripts/05_eval.coffee
      inputs:
        - eval_out/ablations.jsonl
        - run/artifacts.json
      outputs:
        - eval_out/report.md
        - eval_out/generation_policy.json
      depends_on: [metrics]

    metrics:
      run: scripts/041_metrics.py
      depends_on: [pre_eval]


    entropy:
      run: scripts/115_entropy.py
      depends_on: [never]

    prepare_outmd:
      run: scripts/80_prepare_outmd.py
      depends_on: [never]

    train_sft:
      run: scripts/81_train_sft.py
      depends_on: [never]

    chat_jim:
      run: scripts/chat_jim.py
      depends_on: [never]

