# Config override for the full scripts/ pipeline

# Global config shared by all steps
run:
  data_dir: run/data
  eval_dir: run/eval_out
  experiments: run/experiments.csv
  artifacts: run/artifacts.json
  model: microsoft/Phi-3-mini-4k-instruct
  epochs: 3
  batch_size: 8

pipeline:
  steps:
    manifest:
      run: scripts/00_manifest.py

    fetch_hf_dataset:
      run: scripts/01_fetch_hf_dataset.py
      depends_on: [manifest]

    prepare_prompts:
      run: scripts/022_prepare_prompts.py
      depends_on: [fetch_hf_dataset]

    prepare_experiments:
      run: scripts/023_prepare_experiments.py
      depends_on: [prepare_prompts]

    prepare_data:
      run: scripts/02_prepare_data.py
      depends_on: [prepare_experiments]

    register:
      run: scripts/031_register.py
      depends_on: [prepare_data]

    fuse:
      run: scripts/032_fuse.py
      depends_on: [train]

    train:
      run: scripts/03_train.py
      depends_on: [register]

    metrics:
      run: scripts/041_metrics.py
      depends_on: [snapshot]

    sanity:
      run: scripts/042_sanity.py
      depends_on: [metrics,fuse]

    snapshot:
      run: scripts/04_snapshot.py
      depends_on: [train]

    eval:
      run: scripts/05_eval.py
      depends_on: [sanity]

    entropy:
      run: scripts/115_entropy.py
      depends_on: [fuse,eval,snapshot]

    prepare_outmd:
      run: scripts/80_prepare_outmd.py
      depends_on: [entropy]

    train_sft:
      run: scripts/81_train_sft.py
      depends_on: [never]

    chat_jim:
      run: scripts/chat_jim.py
      depends_on: [never]
