# Config override for the full scripts/ pipeline

# Global config shared by all steps
run:
  data_dir: run/data
  eval_dir: run/eval_out
  experiments: run/experiments.csv
  artifacts: run/artifacts.json
  model: microsoft/Phi-3-mini-4k-instruct
  epochs: 3
  batch_size: 8

pipeline:
  steps:
    manifest:
      run: scripts/00_manifest.py

    fetch_hf_dataset:
      run: scripts/01_fetch_hf_dataset.py
      depends_on: [manifest]

    prepare_prompts:
      run: scripts/022_prepare_prompts.py
      depends_on: [fetch_hf_dataset]

    prepare_experiments:
      run: scripts/023_prepare_experiments.py
      depends_on: [prepare_prompts]

    prepare_data:
      run: scripts/02_prepare_data.py
      depends_on: [prepare_experiments]

    register:
      run: scripts/031_register.py
      depends_on: [prepare_data]

    train:
      run: scripts/03_train.py
      depends_on: [register]

    fuse:
      run: scripts/032_fuse.py
      depends_on: [train]

    examination:
      run: scripts/042_examination.py
      depends_on: [fuse]

    sanity:
      run: scripts/042_sanity.py
      depends_on: [snapshot]

    snapshot:
      run: scripts/04_snapshot.py
      depends_on: [examination]
