name: mlxtrain
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip>=24.0
  - pip:
      - mlx-lm==0.26.3
      - datasets==4.0.0
      - pandas==2.3.1
      - numpy==2.3.2
      - tqdm==4.67.1
      - notebook
